In [987]:
import pandas as pd
import numpy as np
df_1 = pd.read_csv("Raw_AirbnbData.csv")

In [988]:
df_1.head(10)

id                            listing_url     scrape_id  \
0  27640141.0  https://www.airbnb.com/rooms/27640141  2.022090e+13   
1  27826009.0  https://www.airbnb.com/rooms/27826009  2.022090e+13   
2  27647117.0  https://www.airbnb.com/rooms/27647117  2.022090e+13   
3  27647509.0  https://www.airbnb.com/rooms/27647509  2.022090e+13   
4  27653375.0  https://www.airbnb.com/rooms/27653375  2.022090e+13   
5  27827073.0  https://www.airbnb.com/rooms/27827073  2.022090e+13   
6  27658681.0  https://www.airbnb.com/rooms/27658681  2.022090e+13   
7  27831815.0  https://www.airbnb.com/rooms/27831815  2.022090e+13   
8  27832397.0  https://www.airbnb.com/rooms/27832397  2.022090e+13   
9  27675456.0  https://www.airbnb.com/rooms/27675456  2.022090e+13   

  last_scraped           source  \
0   2022-09-07      city scrape   
1   2022-09-08  previous scrape   
2   2022-09-08  previous scrape   
3   2022-09-08  previous scrape   
4   2022-09-08      city scrape   
5   2022-09-07      city scrape   
6   2022-09-07      city scrape   
7   2022-09-08      city scrape   
8   2022-09-08  previous scrape   
9   2022-09-07      city scrape   

                                                name  \
0    Fibre internet*Monthly Discount*Character House   
1                                     Downtown condo   
2           Cozy studio in an amazing neighbourhood!   
3  Dundas west subway station apartment BEST LOCA...   
4     Exquisite 1200 sqft 3BR + Den in core-downtown   
5         Designer Retreat in the Heart of The Beach   
6           The Beach- Bright Suite with Kitchenette   
7  Bright, Central, Spacious Condo - Heart of Tor...   
8                                     The Ark Studio   
9  Private bachelor near Warden Station 10min by ...   

                                         description  \
0  Monthly and longer stays welcome! New desk & o...   
1  Welcome to the heart of the city! Located in t...   
2  The studio apartment is in Greek Town on The D...   
3  It is a two bedrooms apartment on the ground f...   
4  Exquisite 1200 sqft 3 Bedroom + Den Condo in c...   
5  Beautifully designed, clean and quiet 2 bedroo...   
6  Fully renovated bright 1 bedroom basement suit...   
7  Stay in this high up, bright & spacious condo ...   
8  The Ark is a compact but fully functional, hom...   
9  Located 10 minutes from Warden Subway Station,...   

                               neighborhood_overview  \
0  Within one block walking you will be on Bloor ...   
1  It is a beautiful neighbourhood filled with up...   
2                                                NaN   
3                                  Familiar building   
4  The building is connected indoors via the PATH...   
5  Also known as “The Beaches,” this relaxed neig...   
6  You can have it all in the Beaches. Enjoy the ...   
7  The lively Entertainment District lives up to ...   
8  On our doorstep is a wide selection of restaur...   
9                                                NaN   

                                         picture_url    host_id  ...  \
0  https://a0.muscache.com/pictures/89a05e34-3549...    2343887  ...   
1  https://a0.muscache.com/pictures/6e7c51ed-320d...   17410774  ...   
2  https://a0.muscache.com/pictures/c3a558bd-0918...   96809956  ...   
3  https://a0.muscache.com/pictures/81f1eb2f-9a0b...  179249078  ...   
4  https://a0.muscache.com/pictures/073dc44e-a9a5...  135718015  ...   
5  https://a0.muscache.com/pictures/miso/Hosting-...    1569948  ...   
6  https://a0.muscache.com/pictures/f09108d5-37cf...  134949475  ...   
7  https://a0.muscache.com/pictures/f9b70591-c59c...   35028799  ...   
8  https://a0.muscache.com/pictures/459a8c4c-49d4...   34233250  ...   
9  https://a0.muscache.com/pictures/019cfee4-0c8e...  141030429  ...   

  review_scores_communication review_scores_location review_scores_value  \
0                        4.89                   4.89                4.77   
1                        5.00                   5.00      

In [989]:
#dropping columns no used for data analysis 
df = df_1.drop(['id',"source","name", "bathrooms_text", "host_verifications","host_location","has_availability","host_neighbourhood", "listing_url","neighbourhood","calculated_host_listings_count","host_listings_count", "scrape_id",'last_scraped',"picture_url","host_url", "host_id",'description','neighborhood_overview','host_name', "host_about","host_thumbnail_url", "host_picture_url", "neighbourhood_group_cleansed","bathrooms","calculated_host_listings_count_entire_homes","calculated_host_listings_count_private_rooms","calculated_host_listings_count_shared_rooms",'first_review','last_review',"license","calendar_last_scraped","calendar_updated","minimum_minimum_nights","maximum_minimum_nights","minimum_maximum_nights","maximum_maximum_nights","minimum_nights_avg_ntm","maximum_nights_avg_ntm"], axis = 1) 
df.shape

(16035, 36)

In [990]:
df.isnull().sum()

host_since                        2
host_response_time             4778
host_response_rate             4778
host_acceptance_rate           4563
host_is_superhost                 1
host_total_listings_count         2
host_has_profile_pic              2
host_identity_verified            2
neighbourhood_cleansed            0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bedrooms                        995
beds                            208
amenities                         0
price                             0
minimum_nights                    0
maximum_nights                    0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
review_scores_rating        

In [991]:
#drop NA from the host since and review columns
df = df.dropna(subset=["host_since",'review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value'])

In [992]:
#replace NA in host response time with no response
df['host_response_time'] = df['host_response_time'].replace(np.NaN,"no response")
df.host_response_time.unique()  

array(['within a few hours', 'no response', 'within an hour',
       'a few days or more', 'within a day'], dtype=object)

In [993]:
df['host_response_time']

0        within a few hours
1               no response
2               no response
3               no response
4            within an hour
                ...        
16029        within an hour
16031        within an hour
16032        within an hour
16033        within an hour
16034        within an hour
Name: host_response_time, Length: 12496, dtype: object

In [994]:
#convert the percentage response rate into a float 
df['host_response_rate'] = df['host_response_rate'].str.rstrip("%").astype(float)/100 # Stripping % and converting to float
df['host_response_rate'] = df['host_response_rate'].replace(np.NaN,0) # Filling 0 for NaN
df.host_response_rate.unique()  

array([1.  , 0.  , 0.94, 0.2 , 0.9 , 0.5 , 0.33, 0.99, 0.67, 0.93, 0.89,
       0.83, 0.8 , 0.92, 0.88, 0.43, 0.91, 0.95, 0.17, 0.76, 0.96, 0.69,
       0.98, 0.56, 0.78, 0.97, 0.6 , 0.35, 0.7 , 0.73, 0.38, 0.71, 0.75,
       0.86, 0.82, 0.29, 0.3 , 0.25, 0.13, 0.4 , 0.64, 0.85, 0.22, 0.07,
       0.32, 0.79, 0.08, 0.52, 0.87, 0.45, 0.77, 0.84, 0.72, 0.65, 0.57,
       0.41, 0.62, 0.61, 0.48, 0.68])

In [995]:
#convert the percentage acceptance rate into a float 
df['host_acceptance_rate'] = df['host_acceptance_rate'].str.rstrip("%").astype(float)/100 # Stripping % and converting to float
df['host_acceptance_rate'] = df['host_acceptance_rate'].replace(np.NaN,0) # Filling 0 for NaN
df.host_acceptance_rate.unique()  

array([0.69, 0.  , 0.91, 0.98, 0.92, 1.  , 0.93, 0.89, 0.75, 0.95, 0.33,
       0.9 , 0.96, 0.87, 0.97, 0.85, 0.77, 0.94, 0.71, 0.65, 0.46, 0.22,
       0.83, 0.81, 0.99, 0.76, 0.88, 0.25, 0.67, 0.64, 0.39, 0.82, 0.86,
       0.8 , 0.58, 0.4 , 0.59, 0.55, 0.5 , 0.53, 0.72, 0.43, 0.78, 0.79,
       0.73, 0.35, 0.38, 0.17, 0.84, 0.66, 0.29, 0.63, 0.68, 0.3 , 0.32,
       0.62, 0.56, 0.74, 0.6 , 0.7 , 0.12, 0.52, 0.57, 0.41, 0.51, 0.18,
       0.37, 0.36, 0.42, 0.2 , 0.61, 0.54, 0.21, 0.44, 0.19, 0.08, 0.31,
       0.15, 0.49, 0.45, 0.01, 0.47, 0.23, 0.1 , 0.27, 0.11, 0.09, 0.13,
       0.07, 0.14, 0.26, 0.24, 0.48])

In [996]:
#convert super host status to boolean
dictionary_replace = {'t': True, 'f': False}
boolean_host_is_superhost = df['host_is_superhost'].map(dictionary_replace)
df["host_is_superhost"] = boolean_host_is_superhost
df.host_is_superhost.unique()  

array([ True, False])

In [997]:
#replace NA in host listing count to 1 - the minimum possible
df['host_total_listings_count'] = df['host_total_listings_count'].replace(np.nan,1.0)
df.host_total_listings_count.unique() 

array([  2.,   1.,   4.,  70.,   3.,   6.,  10.,   9.,   7.,  29.,  12.,
         5.,  24.,   8.,  13.,  19.,  15.,  11.,  26., 145.,  18.,  34.,
        14.,  41.,  73.,  27., 265.,  23.,  36., 196.,  25.,  87.,  33.,
        78.,  17.,  20.,  54.,  16.,  56.,  22.,  46.,  93.,  40.,  50.,
        28.,  30.,  42., 445.,  39., 214., 157., 573.,  99.,  32., 274.,
        31.,  35.,  21.,  48.,  83., 108., 100.,  58.,  47., 115.,  38.,
        62.,  81., 111.,  57.,  75.,  49.,  65.,  37.,  44.,  89.,  45.,
       118.])

In [998]:
#convert host profile picture into a boolean
dictionary_replace = {'t': True, 'f': False}
boolean_host_has_profile_pic = df['host_has_profile_pic'].map(dictionary_replace)
df["host_has_profile_pic"] = boolean_host_has_profile_pic
df['host_has_profile_pic'] = df['host_has_profile_pic'].replace(np.nan,False)
df.host_has_profile_pic.unique() 

array([ True, False])

In [999]:
#convert host identify verified to a boolean
dictionary_replace = {'t': True, 'f': False}
boolean_host_identity_verified = df['host_identity_verified'].map(dictionary_replace)
df["host_identity_verified"] = boolean_host_identity_verified
df['host_identity_verified'] = df['host_identity_verified'].replace(np.nan,"None")
df.host_identity_verified.unique() 

array([ True, False])

In [1000]:
#replace 0 accomidations to a minimum of 1 
df['accommodates'] = df['accommodates'].replace(0,1)
df.accommodates.unique()  

array([ 2,  3,  8,  4,  1,  6,  7,  5, 10,  9, 16, 12, 11, 14, 13, 15])

In [1001]:
df.isnull().sum()

host_since                       0
host_response_time               0
host_response_rate               0
host_acceptance_rate             0
host_is_superhost                0
host_total_listings_count        0
host_has_profile_pic             0
host_identity_verified           0
neighbourhood_cleansed           0
latitude                         0
longitude                        0
property_type                    0
room_type                        0
accommodates                     0
bedrooms                       792
beds                           135
amenities                        0
price                            0
minimum_nights                   0
maximum_nights                   0
availability_30                  0
availability_60                  0
availability_90                  0
availability_365                 0
number_of_reviews                0
number_of_reviews_ltm            0
number_of_reviews_l30d           0
review_scores_rating             0
review_scores_accura

In [1002]:
df.head(100)

host_since  host_response_time  host_response_rate  host_acceptance_rate  \
0    2012-05-10  within a few hours                 1.0                  0.69   
1    2014-06-29         no response                 0.0                  0.00   
2    2016-09-26         no response                 0.0                  0.00   
3    2018-03-18         no response                 0.0                  0.00   
4    2017-06-18      within an hour                 1.0                  0.91   
..          ...                 ...                 ...                   ...   
103  2011-08-11      within an hour                 1.0                  0.90   
104  2010-11-29  within a few hours                 1.0                  0.96   
105  2011-01-30         no response                 0.0                  0.00   
106  2011-08-25  within a few hours                 1.0                  0.76   
107  2010-08-08  within a few hours                 1.0                  0.81   

     host_is_superhost  host_total_listings_count  host_has_profile_pic  \
0                 True                        2.0                  True   
1                False                        1.0                  True   
2                False                        1.0                  True   
3                False                        4.0                  True   
4                False                       70.0                  True   
..                 ...                        ...                   ...   
103               True                        1.0                  True   
104               True                       15.0                  True   
105              False                        2.0                  True   
106               True                        3.0                  True   
107              False                       19.0                  True   

     host_identity_verified               neighbourhood_cleansed  latitude  \
0                      True  Dovercourt-Wallace Emerson-Junction  43.66434   
1                      True    Waterfront Communities-The Island  43.64698   
2                     False             Playter Estates-Danforth  43.67943   
3                      True                      High Park North  43.65953   
4                      True    Waterfront Communities-The Island  43.64126   
..                      ...                                  ...       ...   
103                    True                             Oakridge  43.69431   
104                    True                              Niagara  43.64453   
105                    True                       Dufferin Grove  43.65767   
106                    True                      Little Portugal  43.64710   
107                    True                  Rosedale-Moore Park  43.67138   

     ...  number_of_reviews_l30d review_scores_rating review_scores_accuracy  \
0    ...                       0                 4.85                   4.96   
1    ...                       0                 5.00                   5.00   
2    ...                       0                 5.00                   5.00   
3    ...                       0                 4.63                   4.38   
4    ...                       0                 4.95                   5.00   
..   ...                     ...                  ...                    ...   
103  ...                       1                 4.97                   4.94   
104  ...                       0                 4.78                   4.79   
105  ...                       0                 4.86                   4.93   
106  ...                       0                 4.75                   4.80   
107  ...                       0                 4.53                   4.65   

     review_scores_cleanliness  review_scores_checkin  \
0                         4.91                   4.94   
1                         5.00                   5.00   
2                         5.00                   5.00   
3    

In [1003]:
#convert price to type float and drop $ sign
df['price'] = df['price'].str.replace(',', '', regex=True)
df['price'] = df['price'].str.replace('$', '', regex=True)
df['price'].head(5)

0      90.00 
1     130.00 
2      45.00 
3      80.00 
4    1999.00 
Name: price, dtype: object

In [1004]:
df["price"] = df['price'].apply(pd.to_numeric)
result = df.price.dtypes
print(result)

float64


In [1005]:
df[(df.beds==0) & (df.bedrooms==0)]
df = df.drop(df[(df.beds==0) & (df.bedrooms==0)].index)
df.reset_index(inplace=True, drop=True)
df.shape

(12496, 36)

In [1006]:
#we will use price and accomodates to predict missing values for bedrooms
new_df =df[['price','accommodates',"bedrooms"]].copy()
new_df

price  accommodates  bedrooms
0        90.0             2       1.0
1       130.0             2       1.0
2        45.0             2       NaN
3        80.0             3       1.0
4      1999.0             8       3.0
...       ...           ...       ...
12491    61.0             2       1.0
12492    51.0             2       1.0
12493    51.0             2       1.0
12494    51.0             2       1.0
12495   240.0             3       2.0

[12496 rows x 3 columns]

In [1007]:
train_data = new_df.dropna()
train_data

price  accommodates  bedrooms
0        90.0             2       1.0
1       130.0             2       1.0
3        80.0             3       1.0
4      1999.0             8       3.0
5       359.0             3       2.0
...       ...           ...       ...
12491    61.0             2       1.0
12492    51.0             2       1.0
12493    51.0             2       1.0
12494    51.0             2       1.0
12495   240.0             3       2.0

[11704 rows x 3 columns]

In [1008]:
test_data = new_df[new_df["bedrooms"].isnull()]
test_data

price  accommodates  bedrooms
2       45.0             2       NaN
8       90.0             2       NaN
9       54.0             2       NaN
36      75.0             2       NaN
49     139.0             2       NaN
...      ...           ...       ...
12321   94.0             1       NaN
12346  131.0             2       NaN
12427   93.0             1       NaN
12483   83.0             2       NaN
12488   84.0             2       NaN

[792 rows x 3 columns]

In [1009]:
X_train = train_data.drop("bedrooms", axis = 1)
X_train

price  accommodates
0        90.0             2
1       130.0             2
3        80.0             3
4      1999.0             8
5       359.0             3
...       ...           ...
12491    61.0             2
12492    51.0             2
12493    51.0             2
12494    51.0             2
12495   240.0             3

[11704 rows x 2 columns]

In [1010]:
Y_train = train_data["bedrooms"]
Y_train

0        1.0
1        1.0
3        1.0
4        3.0
5        2.0
        ... 
12491    1.0
12492    1.0
12493    1.0
12494    1.0
12495    2.0
Name: bedrooms, Length: 11704, dtype: float64

In [1011]:
X_test = test_data.drop("bedrooms", axis = 1)
X_test

price  accommodates
2       45.0             2
8       90.0             2
9       54.0             2
36      75.0             2
49     139.0             2
...      ...           ...
12321   94.0             1
12346  131.0             2
12427   93.0             1
12483   83.0             2
12488   84.0             2

[792 rows x 2 columns]

In [1012]:
Y_test = test_data["bedrooms"]
Y_test.unique()

array([nan])

In [1013]:
from sklearn import linear_model
LINREG = linear_model.LinearRegression()
LINREG.fit(X_train,Y_train)

LinearRegression()

In [1014]:
y_predict = LINREG.predict(X_test)
y_predictrounded = y_predict.round(0)

In [1015]:
X_test["predicted_bedrooms"] = y_predictrounded
X_test

price  accommodates  predicted_bedrooms
2       45.0             2                 1.0
8       90.0             2                 1.0
9       54.0             2                 1.0
36      75.0             2                 1.0
49     139.0             2                 1.0
...      ...           ...                 ...
12321   94.0             1                 1.0
12346  131.0             2                 1.0
12427   93.0             1                 1.0
12483   83.0             2                 1.0
12488   84.0             2                 1.0

[792 rows x 3 columns]

In [1016]:
df["bedrooms"].fillna(X_test["predicted_bedrooms"], inplace=True)

In [1017]:
df.bedrooms.unique()

array([1., 3., 2., 4., 5., 6., 8., 7., 9.])

In [1018]:
#we will use price and accomodates to predict missing values for beds
new_df1 =df[['price','accommodates',"beds"]].copy()
new_df1

price  accommodates  beds
0        90.0             2   1.0
1       130.0             2   2.0
2        45.0             2   1.0
3        80.0             3   1.0
4      1999.0             8   4.0
...       ...           ...   ...
12491    61.0             2   1.0
12492    51.0             2   1.0
12493    51.0             2   1.0
12494    51.0             2   1.0
12495   240.0             3   3.0

[12496 rows x 3 columns]

In [1019]:
train_data1 = new_df1.dropna()
train_data1

price  accommodates  beds
0        90.0             2   1.0
1       130.0             2   2.0
2        45.0             2   1.0
3        80.0             3   1.0
4      1999.0             8   4.0
...       ...           ...   ...
12491    61.0             2   1.0
12492    51.0             2   1.0
12493    51.0             2   1.0
12494    51.0             2   1.0
12495   240.0             3   3.0

[12361 rows x 3 columns]

In [1020]:
test_data1 = new_df1[new_df1["beds"].isnull()]
test_data1

price  accommodates  beds
73      55.0             1   NaN
281    143.0             2   NaN
417     50.0             2   NaN
507     76.0             1   NaN
683    130.0             2   NaN
...      ...           ...   ...
12275  400.0            16   NaN
12281  328.0            16   NaN
12285  150.0             2   NaN
12306   92.0             2   NaN
12467  150.0             1   NaN

[135 rows x 3 columns]

In [1021]:
X_train1 = train_data1.drop("beds", axis = 1)
X_train1

price  accommodates
0        90.0             2
1       130.0             2
2        45.0             2
3        80.0             3
4      1999.0             8
...       ...           ...
12491    61.0             2
12492    51.0             2
12493    51.0             2
12494    51.0             2
12495   240.0             3

[12361 rows x 2 columns]

In [1022]:
Y_train1 = train_data1["beds"]
Y_train1

0        1.0
1        2.0
2        1.0
3        1.0
4        4.0
        ... 
12491    1.0
12492    1.0
12493    1.0
12494    1.0
12495    3.0
Name: beds, Length: 12361, dtype: float64

In [1023]:
X_test1 = test_data1.drop("beds", axis = 1)
X_test1

price  accommodates
73      55.0             1
281    143.0             2
417     50.0             2
507     76.0             1
683    130.0             2
...      ...           ...
12275  400.0            16
12281  328.0            16
12285  150.0             2
12306   92.0             2
12467  150.0             1

[135 rows x 2 columns]

In [1024]:
Y_test1 = test_data1["beds"]
Y_test1.unique()

array([nan])

In [1025]:
from sklearn import linear_model
LINREG = linear_model.LinearRegression()
LINREG.fit(X_train1,Y_train1)

LinearRegression()

In [1026]:
y_predict = LINREG.predict(X_test1)
y_predictrounded = y_predict.round(0)

In [1027]:
X_test1["predicted_beds"] = y_predictrounded
X_test1

price  accommodates  predicted_beds
73      55.0             1             1.0
281    143.0             2             1.0
417     50.0             2             1.0
507     76.0             1             1.0
683    130.0             2             1.0
...      ...           ...             ...
12275  400.0            16             8.0
12281  328.0            16             8.0
12285  150.0             2             1.0
12306   92.0             2             1.0
12467  150.0             1             1.0

[135 rows x 3 columns]

In [1028]:
df["beds"].fillna(X_test1["predicted_beds"], inplace=True)

In [1029]:
df.beds.unique()

array([ 1.,  2.,  4.,  3.,  7.,  8.,  5.,  6.,  9., 10., 16., 11.])

In [1030]:
#converting the list of amenities to the number of amenities at the location
df['amenities'] = df['amenities'].astype('string')
df.amenities.head(5)

0    ["Carbon monoxide alarm", "Microwave", "Iron",...
1    ["Smoke alarm", "Air conditioning", "Kitchen",...
2    ["Laundromat nearby", "Hot water", "Iron", "Sm...
3    ["Carbon monoxide alarm", "Microwave", "Iron",...
4    ["Carbon monoxide alarm", "Microwave", "Iron",...
Name: amenities, dtype: string

In [1031]:
df["amenities"] = df['amenities'].apply(eval)

In [1032]:
for i, l in enumerate(df["amenities"]):
 print("list",i,"is",type(l))

list 0 is <class 'list'>
list 1 is <class 'list'>
list 2 is <class 'list'>
list 3 is <class 'list'>
list 4 is <class 'list'>
list 5 is <class 'list'>
list 6 is <class 'list'>
list 7 is <class 'list'>
list 8 is <class 'list'>
list 9 is <class 'list'>
list 10 is <class 'list'>
list 11 is <class 'list'>
list 12 is <class 'list'>
list 13 is <class 'list'>
list 14 is <class 'list'>
list 15 is <class 'list'>
list 16 is <class 'list'>
list 17 is <class 'list'>
list 18 is <class 'list'>
list 19 is <class 'list'>
list 20 is <class 'list'>
list 21 is <class 'list'>
list 22 is <class 'list'>
list 23 is <class 'list'>
list 24 is <class 'list'>
list 25 is <class 'list'>
list 26 is <class 'list'>
list 27 is <class 'list'>
list 28 is <class 'list'>
list 29 is <class 'list'>
list 30 is <class 'list'>
list 31 is <class 'list'>
list 32 is <class 'list'>
list 33 is <class 'list'>
list 34 is <class 'list'>
list 35 is <class 'list'>
list 36 is <class 'list'>
list 37 is <class 'list'>
list 38 is <class 'lis

list 385 is <class 'list'>
list 386 is <class 'list'>
list 387 is <class 'list'>
list 388 is <class 'list'>
list 389 is <class 'list'>
list 390 is <class 'list'>
list 391 is <class 'list'>
list 392 is <class 'list'>
list 393 is <class 'list'>
list 394 is <class 'list'>
list 395 is <class 'list'>
list 396 is <class 'list'>
list 397 is <class 'list'>
list 398 is <class 'list'>
list 399 is <class 'list'>
list 400 is <class 'list'>
list 401 is <class 'list'>
list 402 is <class 'list'>
list 403 is <class 'list'>
list 404 is <class 'list'>
list 405 is <class 'list'>
list 406 is <class 'list'>
list 407 is <class 'list'>
list 408 is <class 'list'>
list 409 is <class 'list'>
list 410 is <class 'list'>
list 411 is <class 'list'>
list 412 is <class 'list'>
list 413 is <class 'list'>
list 414 is <class 'list'>
list 415 is <class 'list'>
list 416 is <class 'list'>
list 417 is <class 'list'>
list 418 is <class 'list'>
list 419 is <class 'list'>
list 420 is <class 'list'>
list 421 is <class 'list'>
l

list 806 is <class 'list'>
list 807 is <class 'list'>
list 808 is <class 'list'>
list 809 is <class 'list'>
list 810 is <class 'list'>
list 811 is <class 'list'>
list 812 is <class 'list'>
list 813 is <class 'list'>
list 814 is <class 'list'>
list 815 is <class 'list'>
list 816 is <class 'list'>
list 817 is <class 'list'>
list 818 is <class 'list'>
list 819 is <class 'list'>
list 820 is <class 'list'>
list 821 is <class 'list'>
list 822 is <class 'list'>
list 823 is <class 'list'>
list 824 is <class 'list'>
list 825 is <class 'list'>
list 826 is <class 'list'>
list 827 is <class 'list'>
list 828 is <class 'list'>
list 829 is <class 'list'>
list 830 is <class 'list'>
list 831 is <class 'list'>
list 832 is <class 'list'>
list 833 is <class 'list'>
list 834 is <class 'list'>
list 835 is <class 'list'>
list 836 is <class 'list'>
list 837 is <class 'list'>
list 838 is <class 'list'>
list 839 is <class 'list'>
list 840 is <class 'list'>
list 841 is <class 'list'>
list 842 is <class 'list'>
l

list 1181 is <class 'list'>
list 1182 is <class 'list'>
list 1183 is <class 'list'>
list 1184 is <class 'list'>
list 1185 is <class 'list'>
list 1186 is <class 'list'>
list 1187 is <class 'list'>
list 1188 is <class 'list'>
list 1189 is <class 'list'>
list 1190 is <class 'list'>
list 1191 is <class 'list'>
list 1192 is <class 'list'>
list 1193 is <class 'list'>
list 1194 is <class 'list'>
list 1195 is <class 'list'>
list 1196 is <class 'list'>
list 1197 is <class 'list'>
list 1198 is <class 'list'>
list 1199 is <class 'list'>
list 1200 is <class 'list'>
list 1201 is <class 'list'>
list 1202 is <class 'list'>
list 1203 is <class 'list'>
list 1204 is <class 'list'>
list 1205 is <class 'list'>
list 1206 is <class 'list'>
list 1207 is <class 'list'>
list 1208 is <class 'list'>
list 1209 is <class 'list'>
list 1210 is <class 'list'>
list 1211 is <class 'list'>
list 1212 is <class 'list'>
list 1213 is <class 'list'>
list 1214 is <class 'list'>
list 1215 is <class 'list'>
list 1216 is <class 

list 1556 is <class 'list'>
list 1557 is <class 'list'>
list 1558 is <class 'list'>
list 1559 is <class 'list'>
list 1560 is <class 'list'>
list 1561 is <class 'list'>
list 1562 is <class 'list'>
list 1563 is <class 'list'>
list 1564 is <class 'list'>
list 1565 is <class 'list'>
list 1566 is <class 'list'>
list 1567 is <class 'list'>
list 1568 is <class 'list'>
list 1569 is <class 'list'>
list 1570 is <class 'list'>
list 1571 is <class 'list'>
list 1572 is <class 'list'>
list 1573 is <class 'list'>
list 1574 is <class 'list'>
list 1575 is <class 'list'>
list 1576 is <class 'list'>
list 1577 is <class 'list'>
list 1578 is <class 'list'>
list 1579 is <class 'list'>
list 1580 is <class 'list'>
list 1581 is <class 'list'>
list 1582 is <class 'list'>
list 1583 is <class 'list'>
list 1584 is <class 'list'>
list 1585 is <class 'list'>
list 1586 is <class 'list'>
list 1587 is <class 'list'>
list 1588 is <class 'list'>
list 1589 is <class 'list'>
list 1590 is <class 'list'>
list 1591 is <class 

list 1931 is <class 'list'>
list 1932 is <class 'list'>
list 1933 is <class 'list'>
list 1934 is <class 'list'>
list 1935 is <class 'list'>
list 1936 is <class 'list'>
list 1937 is <class 'list'>
list 1938 is <class 'list'>
list 1939 is <class 'list'>
list 1940 is <class 'list'>
list 1941 is <class 'list'>
list 1942 is <class 'list'>
list 1943 is <class 'list'>
list 1944 is <class 'list'>
list 1945 is <class 'list'>
list 1946 is <class 'list'>
list 1947 is <class 'list'>
list 1948 is <class 'list'>
list 1949 is <class 'list'>
list 1950 is <class 'list'>
list 1951 is <class 'list'>
list 1952 is <class 'list'>
list 1953 is <class 'list'>
list 1954 is <class 'list'>
list 1955 is <class 'list'>
list 1956 is <class 'list'>
list 1957 is <class 'list'>
list 1958 is <class 'list'>
list 1959 is <class 'list'>
list 1960 is <class 'list'>
list 1961 is <class 'list'>
list 1962 is <class 'list'>
list 1963 is <class 'list'>
list 1964 is <class 'list'>
list 1965 is <class 'list'>
list 1966 is <class 

list 2306 is <class 'list'>
list 2307 is <class 'list'>
list 2308 is <class 'list'>
list 2309 is <class 'list'>
list 2310 is <class 'list'>
list 2311 is <class 'list'>
list 2312 is <class 'list'>
list 2313 is <class 'list'>
list 2314 is <class 'list'>
list 2315 is <class 'list'>
list 2316 is <class 'list'>
list 2317 is <class 'list'>
list 2318 is <class 'list'>
list 2319 is <class 'list'>
list 2320 is <class 'list'>
list 2321 is <class 'list'>
list 2322 is <class 'list'>
list 2323 is <class 'list'>
list 2324 is <class 'list'>
list 2325 is <class 'list'>
list 2326 is <class 'list'>
list 2327 is <class 'list'>
list 2328 is <class 'list'>
list 2329 is <class 'list'>
list 2330 is <class 'list'>
list 2331 is <class 'list'>
list 2332 is <class 'list'>
list 2333 is <class 'list'>
list 2334 is <class 'list'>
list 2335 is <class 'list'>
list 2336 is <class 'list'>
list 2337 is <class 'list'>
list 2338 is <class 'list'>
list 2339 is <class 'list'>
list 2340 is <class 'list'>
list 2341 is <class 

list 2681 is <class 'list'>
list 2682 is <class 'list'>
list 2683 is <class 'list'>
list 2684 is <class 'list'>
list 2685 is <class 'list'>
list 2686 is <class 'list'>
list 2687 is <class 'list'>
list 2688 is <class 'list'>
list 2689 is <class 'list'>
list 2690 is <class 'list'>
list 2691 is <class 'list'>
list 2692 is <class 'list'>
list 2693 is <class 'list'>
list 2694 is <class 'list'>
list 2695 is <class 'list'>
list 2696 is <class 'list'>
list 2697 is <class 'list'>
list 2698 is <class 'list'>
list 2699 is <class 'list'>
list 2700 is <class 'list'>
list 2701 is <class 'list'>
list 2702 is <class 'list'>
list 2703 is <class 'list'>
list 2704 is <class 'list'>
list 2705 is <class 'list'>
list 2706 is <class 'list'>
list 2707 is <class 'list'>
list 2708 is <class 'list'>
list 2709 is <class 'list'>
list 2710 is <class 'list'>
list 2711 is <class 'list'>
list 2712 is <class 'list'>
list 2713 is <class 'list'>
list 2714 is <class 'list'>
list 2715 is <class 'list'>
list 2716 is <class 

list 3055 is <class 'list'>
list 3056 is <class 'list'>
list 3057 is <class 'list'>
list 3058 is <class 'list'>
list 3059 is <class 'list'>
list 3060 is <class 'list'>
list 3061 is <class 'list'>
list 3062 is <class 'list'>
list 3063 is <class 'list'>
list 3064 is <class 'list'>
list 3065 is <class 'list'>
list 3066 is <class 'list'>
list 3067 is <class 'list'>
list 3068 is <class 'list'>
list 3069 is <class 'list'>
list 3070 is <class 'list'>
list 3071 is <class 'list'>
list 3072 is <class 'list'>
list 3073 is <class 'list'>
list 3074 is <class 'list'>
list 3075 is <class 'list'>
list 3076 is <class 'list'>
list 3077 is <class 'list'>
list 3078 is <class 'list'>
list 3079 is <class 'list'>
list 3080 is <class 'list'>
list 3081 is <class 'list'>
list 3082 is <class 'list'>
list 3083 is <class 'list'>
list 3084 is <class 'list'>
list 3085 is <class 'list'>
list 3086 is <class 'list'>
list 3087 is <class 'list'>
list 3088 is <class 'list'>
list 3089 is <class 'list'>
list 3090 is <class 

list 3430 is <class 'list'>
list 3431 is <class 'list'>
list 3432 is <class 'list'>
list 3433 is <class 'list'>
list 3434 is <class 'list'>
list 3435 is <class 'list'>
list 3436 is <class 'list'>
list 3437 is <class 'list'>
list 3438 is <class 'list'>
list 3439 is <class 'list'>
list 3440 is <class 'list'>
list 3441 is <class 'list'>
list 3442 is <class 'list'>
list 3443 is <class 'list'>
list 3444 is <class 'list'>
list 3445 is <class 'list'>
list 3446 is <class 'list'>
list 3447 is <class 'list'>
list 3448 is <class 'list'>
list 3449 is <class 'list'>
list 3450 is <class 'list'>
list 3451 is <class 'list'>
list 3452 is <class 'list'>
list 3453 is <class 'list'>
list 3454 is <class 'list'>
list 3455 is <class 'list'>
list 3456 is <class 'list'>
list 3457 is <class 'list'>
list 3458 is <class 'list'>
list 3459 is <class 'list'>
list 3460 is <class 'list'>
list 3461 is <class 'list'>
list 3462 is <class 'list'>
list 3463 is <class 'list'>
list 3464 is <class 'list'>
list 3465 is <class 

list 3929 is <class 'list'>
list 3930 is <class 'list'>
list 3931 is <class 'list'>
list 3932 is <class 'list'>
list 3933 is <class 'list'>
list 3934 is <class 'list'>
list 3935 is <class 'list'>
list 3936 is <class 'list'>
list 3937 is <class 'list'>
list 3938 is <class 'list'>
list 3939 is <class 'list'>
list 3940 is <class 'list'>
list 3941 is <class 'list'>
list 3942 is <class 'list'>
list 3943 is <class 'list'>
list 3944 is <class 'list'>
list 3945 is <class 'list'>
list 3946 is <class 'list'>
list 3947 is <class 'list'>
list 3948 is <class 'list'>
list 3949 is <class 'list'>
list 3950 is <class 'list'>
list 3951 is <class 'list'>
list 3952 is <class 'list'>
list 3953 is <class 'list'>
list 3954 is <class 'list'>
list 3955 is <class 'list'>
list 3956 is <class 'list'>
list 3957 is <class 'list'>
list 3958 is <class 'list'>
list 3959 is <class 'list'>
list 3960 is <class 'list'>
list 3961 is <class 'list'>
list 3962 is <class 'list'>
list 3963 is <class 'list'>
list 3964 is <class 

list 4305 is <class 'list'>
list 4306 is <class 'list'>
list 4307 is <class 'list'>
list 4308 is <class 'list'>
list 4309 is <class 'list'>
list 4310 is <class 'list'>
list 4311 is <class 'list'>
list 4312 is <class 'list'>
list 4313 is <class 'list'>
list 4314 is <class 'list'>
list 4315 is <class 'list'>
list 4316 is <class 'list'>
list 4317 is <class 'list'>
list 4318 is <class 'list'>
list 4319 is <class 'list'>
list 4320 is <class 'list'>
list 4321 is <class 'list'>
list 4322 is <class 'list'>
list 4323 is <class 'list'>
list 4324 is <class 'list'>
list 4325 is <class 'list'>
list 4326 is <class 'list'>
list 4327 is <class 'list'>
list 4328 is <class 'list'>
list 4329 is <class 'list'>
list 4330 is <class 'list'>
list 4331 is <class 'list'>
list 4332 is <class 'list'>
list 4333 is <class 'list'>
list 4334 is <class 'list'>
list 4335 is <class 'list'>
list 4336 is <class 'list'>
list 4337 is <class 'list'>
list 4338 is <class 'list'>
list 4339 is <class 'list'>
list 4340 is <class 

list 4680 is <class 'list'>
list 4681 is <class 'list'>
list 4682 is <class 'list'>
list 4683 is <class 'list'>
list 4684 is <class 'list'>
list 4685 is <class 'list'>
list 4686 is <class 'list'>
list 4687 is <class 'list'>
list 4688 is <class 'list'>
list 4689 is <class 'list'>
list 4690 is <class 'list'>
list 4691 is <class 'list'>
list 4692 is <class 'list'>
list 4693 is <class 'list'>
list 4694 is <class 'list'>
list 4695 is <class 'list'>
list 4696 is <class 'list'>
list 4697 is <class 'list'>
list 4698 is <class 'list'>
list 4699 is <class 'list'>
list 4700 is <class 'list'>
list 4701 is <class 'list'>
list 4702 is <class 'list'>
list 4703 is <class 'list'>
list 4704 is <class 'list'>
list 4705 is <class 'list'>
list 4706 is <class 'list'>
list 4707 is <class 'list'>
list 4708 is <class 'list'>
list 4709 is <class 'list'>
list 4710 is <class 'list'>
list 4711 is <class 'list'>
list 4712 is <class 'list'>
list 4713 is <class 'list'>
list 4714 is <class 'list'>
list 4715 is <class 

list 5055 is <class 'list'>
list 5056 is <class 'list'>
list 5057 is <class 'list'>
list 5058 is <class 'list'>
list 5059 is <class 'list'>
list 5060 is <class 'list'>
list 5061 is <class 'list'>
list 5062 is <class 'list'>
list 5063 is <class 'list'>
list 5064 is <class 'list'>
list 5065 is <class 'list'>
list 5066 is <class 'list'>
list 5067 is <class 'list'>
list 5068 is <class 'list'>
list 5069 is <class 'list'>
list 5070 is <class 'list'>
list 5071 is <class 'list'>
list 5072 is <class 'list'>
list 5073 is <class 'list'>
list 5074 is <class 'list'>
list 5075 is <class 'list'>
list 5076 is <class 'list'>
list 5077 is <class 'list'>
list 5078 is <class 'list'>
list 5079 is <class 'list'>
list 5080 is <class 'list'>
list 5081 is <class 'list'>
list 5082 is <class 'list'>
list 5083 is <class 'list'>
list 5084 is <class 'list'>
list 5085 is <class 'list'>
list 5086 is <class 'list'>
list 5087 is <class 'list'>
list 5088 is <class 'list'>
list 5089 is <class 'list'>
list 5090 is <class 

list 5430 is <class 'list'>
list 5431 is <class 'list'>
list 5432 is <class 'list'>
list 5433 is <class 'list'>
list 5434 is <class 'list'>
list 5435 is <class 'list'>
list 5436 is <class 'list'>
list 5437 is <class 'list'>
list 5438 is <class 'list'>
list 5439 is <class 'list'>
list 5440 is <class 'list'>
list 5441 is <class 'list'>
list 5442 is <class 'list'>
list 5443 is <class 'list'>
list 5444 is <class 'list'>
list 5445 is <class 'list'>
list 5446 is <class 'list'>
list 5447 is <class 'list'>
list 5448 is <class 'list'>
list 5449 is <class 'list'>
list 5450 is <class 'list'>
list 5451 is <class 'list'>
list 5452 is <class 'list'>
list 5453 is <class 'list'>
list 5454 is <class 'list'>
list 5455 is <class 'list'>
list 5456 is <class 'list'>
list 5457 is <class 'list'>
list 5458 is <class 'list'>
list 5459 is <class 'list'>
list 5460 is <class 'list'>
list 5461 is <class 'list'>
list 5462 is <class 'list'>
list 5463 is <class 'list'>
list 5464 is <class 'list'>
list 5465 is <class 

list 5805 is <class 'list'>
list 5806 is <class 'list'>
list 5807 is <class 'list'>
list 5808 is <class 'list'>
list 5809 is <class 'list'>
list 5810 is <class 'list'>
list 5811 is <class 'list'>
list 5812 is <class 'list'>
list 5813 is <class 'list'>
list 5814 is <class 'list'>
list 5815 is <class 'list'>
list 5816 is <class 'list'>
list 5817 is <class 'list'>
list 5818 is <class 'list'>
list 5819 is <class 'list'>
list 5820 is <class 'list'>
list 5821 is <class 'list'>
list 5822 is <class 'list'>
list 5823 is <class 'list'>
list 5824 is <class 'list'>
list 5825 is <class 'list'>
list 5826 is <class 'list'>
list 5827 is <class 'list'>
list 5828 is <class 'list'>
list 5829 is <class 'list'>
list 5830 is <class 'list'>
list 5831 is <class 'list'>
list 5832 is <class 'list'>
list 5833 is <class 'list'>
list 5834 is <class 'list'>
list 5835 is <class 'list'>
list 5836 is <class 'list'>
list 5837 is <class 'list'>
list 5838 is <class 'list'>
list 5839 is <class 'list'>
list 5840 is <class 

list 6179 is <class 'list'>
list 6180 is <class 'list'>
list 6181 is <class 'list'>
list 6182 is <class 'list'>
list 6183 is <class 'list'>
list 6184 is <class 'list'>
list 6185 is <class 'list'>
list 6186 is <class 'list'>
list 6187 is <class 'list'>
list 6188 is <class 'list'>
list 6189 is <class 'list'>
list 6190 is <class 'list'>
list 6191 is <class 'list'>
list 6192 is <class 'list'>
list 6193 is <class 'list'>
list 6194 is <class 'list'>
list 6195 is <class 'list'>
list 6196 is <class 'list'>
list 6197 is <class 'list'>
list 6198 is <class 'list'>
list 6199 is <class 'list'>
list 6200 is <class 'list'>
list 6201 is <class 'list'>
list 6202 is <class 'list'>
list 6203 is <class 'list'>
list 6204 is <class 'list'>
list 6205 is <class 'list'>
list 6206 is <class 'list'>
list 6207 is <class 'list'>
list 6208 is <class 'list'>
list 6209 is <class 'list'>
list 6210 is <class 'list'>
list 6211 is <class 'list'>
list 6212 is <class 'list'>
list 6213 is <class 'list'>
list 6214 is <class 

list 6554 is <class 'list'>
list 6555 is <class 'list'>
list 6556 is <class 'list'>
list 6557 is <class 'list'>
list 6558 is <class 'list'>
list 6559 is <class 'list'>
list 6560 is <class 'list'>
list 6561 is <class 'list'>
list 6562 is <class 'list'>
list 6563 is <class 'list'>
list 6564 is <class 'list'>
list 6565 is <class 'list'>
list 6566 is <class 'list'>
list 6567 is <class 'list'>
list 6568 is <class 'list'>
list 6569 is <class 'list'>
list 6570 is <class 'list'>
list 6571 is <class 'list'>
list 6572 is <class 'list'>
list 6573 is <class 'list'>
list 6574 is <class 'list'>
list 6575 is <class 'list'>
list 6576 is <class 'list'>
list 6577 is <class 'list'>
list 6578 is <class 'list'>
list 6579 is <class 'list'>
list 6580 is <class 'list'>
list 6581 is <class 'list'>
list 6582 is <class 'list'>
list 6583 is <class 'list'>
list 6584 is <class 'list'>
list 6585 is <class 'list'>
list 6586 is <class 'list'>
list 6587 is <class 'list'>
list 6588 is <class 'list'>
list 6589 is <class 

list 6929 is <class 'list'>
list 6930 is <class 'list'>
list 6931 is <class 'list'>
list 6932 is <class 'list'>
list 6933 is <class 'list'>
list 6934 is <class 'list'>
list 6935 is <class 'list'>
list 6936 is <class 'list'>
list 6937 is <class 'list'>
list 6938 is <class 'list'>
list 6939 is <class 'list'>
list 6940 is <class 'list'>
list 6941 is <class 'list'>
list 6942 is <class 'list'>
list 6943 is <class 'list'>
list 6944 is <class 'list'>
list 6945 is <class 'list'>
list 6946 is <class 'list'>
list 6947 is <class 'list'>
list 6948 is <class 'list'>
list 6949 is <class 'list'>
list 6950 is <class 'list'>
list 6951 is <class 'list'>
list 6952 is <class 'list'>
list 6953 is <class 'list'>
list 6954 is <class 'list'>
list 6955 is <class 'list'>
list 6956 is <class 'list'>
list 6957 is <class 'list'>
list 6958 is <class 'list'>
list 6959 is <class 'list'>
list 6960 is <class 'list'>
list 6961 is <class 'list'>
list 6962 is <class 'list'>
list 6963 is <class 'list'>
list 6964 is <class 

list 7304 is <class 'list'>
list 7305 is <class 'list'>
list 7306 is <class 'list'>
list 7307 is <class 'list'>
list 7308 is <class 'list'>
list 7309 is <class 'list'>
list 7310 is <class 'list'>
list 7311 is <class 'list'>
list 7312 is <class 'list'>
list 7313 is <class 'list'>
list 7314 is <class 'list'>
list 7315 is <class 'list'>
list 7316 is <class 'list'>
list 7317 is <class 'list'>
list 7318 is <class 'list'>
list 7319 is <class 'list'>
list 7320 is <class 'list'>
list 7321 is <class 'list'>
list 7322 is <class 'list'>
list 7323 is <class 'list'>
list 7324 is <class 'list'>
list 7325 is <class 'list'>
list 7326 is <class 'list'>
list 7327 is <class 'list'>
list 7328 is <class 'list'>
list 7329 is <class 'list'>
list 7330 is <class 'list'>
list 7331 is <class 'list'>
list 7332 is <class 'list'>
list 7333 is <class 'list'>
list 7334 is <class 'list'>
list 7335 is <class 'list'>
list 7336 is <class 'list'>
list 7337 is <class 'list'>
list 7338 is <class 'list'>
list 7339 is <class 

list 7679 is <class 'list'>
list 7680 is <class 'list'>
list 7681 is <class 'list'>
list 7682 is <class 'list'>
list 7683 is <class 'list'>
list 7684 is <class 'list'>
list 7685 is <class 'list'>
list 7686 is <class 'list'>
list 7687 is <class 'list'>
list 7688 is <class 'list'>
list 7689 is <class 'list'>
list 7690 is <class 'list'>
list 7691 is <class 'list'>
list 7692 is <class 'list'>
list 7693 is <class 'list'>
list 7694 is <class 'list'>
list 7695 is <class 'list'>
list 7696 is <class 'list'>
list 7697 is <class 'list'>
list 7698 is <class 'list'>
list 7699 is <class 'list'>
list 7700 is <class 'list'>
list 7701 is <class 'list'>
list 7702 is <class 'list'>
list 7703 is <class 'list'>
list 7704 is <class 'list'>
list 7705 is <class 'list'>
list 7706 is <class 'list'>
list 7707 is <class 'list'>
list 7708 is <class 'list'>
list 7709 is <class 'list'>
list 7710 is <class 'list'>
list 7711 is <class 'list'>
list 7712 is <class 'list'>
list 7713 is <class 'list'>
list 7714 is <class 

list 8054 is <class 'list'>
list 8055 is <class 'list'>
list 8056 is <class 'list'>
list 8057 is <class 'list'>
list 8058 is <class 'list'>
list 8059 is <class 'list'>
list 8060 is <class 'list'>
list 8061 is <class 'list'>
list 8062 is <class 'list'>
list 8063 is <class 'list'>
list 8064 is <class 'list'>
list 8065 is <class 'list'>
list 8066 is <class 'list'>
list 8067 is <class 'list'>
list 8068 is <class 'list'>
list 8069 is <class 'list'>
list 8070 is <class 'list'>
list 8071 is <class 'list'>
list 8072 is <class 'list'>
list 8073 is <class 'list'>
list 8074 is <class 'list'>
list 8075 is <class 'list'>
list 8076 is <class 'list'>
list 8077 is <class 'list'>
list 8078 is <class 'list'>
list 8079 is <class 'list'>
list 8080 is <class 'list'>
list 8081 is <class 'list'>
list 8082 is <class 'list'>
list 8083 is <class 'list'>
list 8084 is <class 'list'>
list 8085 is <class 'list'>
list 8086 is <class 'list'>
list 8087 is <class 'list'>
list 8088 is <class 'list'>
list 8089 is <class 

list 8432 is <class 'list'>
list 8433 is <class 'list'>
list 8434 is <class 'list'>
list 8435 is <class 'list'>
list 8436 is <class 'list'>
list 8437 is <class 'list'>
list 8438 is <class 'list'>
list 8439 is <class 'list'>
list 8440 is <class 'list'>
list 8441 is <class 'list'>
list 8442 is <class 'list'>
list 8443 is <class 'list'>
list 8444 is <class 'list'>
list 8445 is <class 'list'>
list 8446 is <class 'list'>
list 8447 is <class 'list'>
list 8448 is <class 'list'>
list 8449 is <class 'list'>
list 8450 is <class 'list'>
list 8451 is <class 'list'>
list 8452 is <class 'list'>
list 8453 is <class 'list'>
list 8454 is <class 'list'>
list 8455 is <class 'list'>
list 8456 is <class 'list'>
list 8457 is <class 'list'>
list 8458 is <class 'list'>
list 8459 is <class 'list'>
list 8460 is <class 'list'>
list 8461 is <class 'list'>
list 8462 is <class 'list'>
list 8463 is <class 'list'>
list 8464 is <class 'list'>
list 8465 is <class 'list'>
list 8466 is <class 'list'>
list 8467 is <class 

list 8824 is <class 'list'>
list 8825 is <class 'list'>
list 8826 is <class 'list'>
list 8827 is <class 'list'>
list 8828 is <class 'list'>
list 8829 is <class 'list'>
list 8830 is <class 'list'>
list 8831 is <class 'list'>
list 8832 is <class 'list'>
list 8833 is <class 'list'>
list 8834 is <class 'list'>
list 8835 is <class 'list'>
list 8836 is <class 'list'>
list 8837 is <class 'list'>
list 8838 is <class 'list'>
list 8839 is <class 'list'>
list 8840 is <class 'list'>
list 8841 is <class 'list'>
list 8842 is <class 'list'>
list 8843 is <class 'list'>
list 8844 is <class 'list'>
list 8845 is <class 'list'>
list 8846 is <class 'list'>
list 8847 is <class 'list'>
list 8848 is <class 'list'>
list 8849 is <class 'list'>
list 8850 is <class 'list'>
list 8851 is <class 'list'>
list 8852 is <class 'list'>
list 8853 is <class 'list'>
list 8854 is <class 'list'>
list 8855 is <class 'list'>
list 8856 is <class 'list'>
list 8857 is <class 'list'>
list 8858 is <class 'list'>
list 8859 is <class 

list 9191 is <class 'list'>
list 9192 is <class 'list'>
list 9193 is <class 'list'>
list 9194 is <class 'list'>
list 9195 is <class 'list'>
list 9196 is <class 'list'>
list 9197 is <class 'list'>
list 9198 is <class 'list'>
list 9199 is <class 'list'>
list 9200 is <class 'list'>
list 9201 is <class 'list'>
list 9202 is <class 'list'>
list 9203 is <class 'list'>
list 9204 is <class 'list'>
list 9205 is <class 'list'>
list 9206 is <class 'list'>
list 9207 is <class 'list'>
list 9208 is <class 'list'>
list 9209 is <class 'list'>
list 9210 is <class 'list'>
list 9211 is <class 'list'>
list 9212 is <class 'list'>
list 9213 is <class 'list'>
list 9214 is <class 'list'>
list 9215 is <class 'list'>
list 9216 is <class 'list'>
list 9217 is <class 'list'>
list 9218 is <class 'list'>
list 9219 is <class 'list'>
list 9220 is <class 'list'>
list 9221 is <class 'list'>
list 9222 is <class 'list'>
list 9223 is <class 'list'>
list 9224 is <class 'list'>
list 9225 is <class 'list'>
list 9226 is <class 

list 9627 is <class 'list'>
list 9628 is <class 'list'>
list 9629 is <class 'list'>
list 9630 is <class 'list'>
list 9631 is <class 'list'>
list 9632 is <class 'list'>
list 9633 is <class 'list'>
list 9634 is <class 'list'>
list 9635 is <class 'list'>
list 9636 is <class 'list'>
list 9637 is <class 'list'>
list 9638 is <class 'list'>
list 9639 is <class 'list'>
list 9640 is <class 'list'>
list 9641 is <class 'list'>
list 9642 is <class 'list'>
list 9643 is <class 'list'>
list 9644 is <class 'list'>
list 9645 is <class 'list'>
list 9646 is <class 'list'>
list 9647 is <class 'list'>
list 9648 is <class 'list'>
list 9649 is <class 'list'>
list 9650 is <class 'list'>
list 9651 is <class 'list'>
list 9652 is <class 'list'>
list 9653 is <class 'list'>
list 9654 is <class 'list'>
list 9655 is <class 'list'>
list 9656 is <class 'list'>
list 9657 is <class 'list'>
list 9658 is <class 'list'>
list 9659 is <class 'list'>
list 9660 is <class 'list'>
list 9661 is <class 'list'>
list 9662 is <class 

list 10053 is <class 'list'>
list 10054 is <class 'list'>
list 10055 is <class 'list'>
list 10056 is <class 'list'>
list 10057 is <class 'list'>
list 10058 is <class 'list'>
list 10059 is <class 'list'>
list 10060 is <class 'list'>
list 10061 is <class 'list'>
list 10062 is <class 'list'>
list 10063 is <class 'list'>
list 10064 is <class 'list'>
list 10065 is <class 'list'>
list 10066 is <class 'list'>
list 10067 is <class 'list'>
list 10068 is <class 'list'>
list 10069 is <class 'list'>
list 10070 is <class 'list'>
list 10071 is <class 'list'>
list 10072 is <class 'list'>
list 10073 is <class 'list'>
list 10074 is <class 'list'>
list 10075 is <class 'list'>
list 10076 is <class 'list'>
list 10077 is <class 'list'>
list 10078 is <class 'list'>
list 10079 is <class 'list'>
list 10080 is <class 'list'>
list 10081 is <class 'list'>
list 10082 is <class 'list'>
list 10083 is <class 'list'>
list 10084 is <class 'list'>
list 10085 is <class 'list'>
list 10086 is <class 'list'>
list 10087 is 

list 10449 is <class 'list'>
list 10450 is <class 'list'>
list 10451 is <class 'list'>
list 10452 is <class 'list'>
list 10453 is <class 'list'>
list 10454 is <class 'list'>
list 10455 is <class 'list'>
list 10456 is <class 'list'>
list 10457 is <class 'list'>
list 10458 is <class 'list'>
list 10459 is <class 'list'>
list 10460 is <class 'list'>
list 10461 is <class 'list'>
list 10462 is <class 'list'>
list 10463 is <class 'list'>
list 10464 is <class 'list'>
list 10465 is <class 'list'>
list 10466 is <class 'list'>
list 10467 is <class 'list'>
list 10468 is <class 'list'>
list 10469 is <class 'list'>
list 10470 is <class 'list'>
list 10471 is <class 'list'>
list 10472 is <class 'list'>
list 10473 is <class 'list'>
list 10474 is <class 'list'>
list 10475 is <class 'list'>
list 10476 is <class 'list'>
list 10477 is <class 'list'>
list 10478 is <class 'list'>
list 10479 is <class 'list'>
list 10480 is <class 'list'>
list 10481 is <class 'list'>
list 10482 is <class 'list'>
list 10483 is 

list 10928 is <class 'list'>
list 10929 is <class 'list'>
list 10930 is <class 'list'>
list 10931 is <class 'list'>
list 10932 is <class 'list'>
list 10933 is <class 'list'>
list 10934 is <class 'list'>
list 10935 is <class 'list'>
list 10936 is <class 'list'>
list 10937 is <class 'list'>
list 10938 is <class 'list'>
list 10939 is <class 'list'>
list 10940 is <class 'list'>
list 10941 is <class 'list'>
list 10942 is <class 'list'>
list 10943 is <class 'list'>
list 10944 is <class 'list'>
list 10945 is <class 'list'>
list 10946 is <class 'list'>
list 10947 is <class 'list'>
list 10948 is <class 'list'>
list 10949 is <class 'list'>
list 10950 is <class 'list'>
list 10951 is <class 'list'>
list 10952 is <class 'list'>
list 10953 is <class 'list'>
list 10954 is <class 'list'>
list 10955 is <class 'list'>
list 10956 is <class 'list'>
list 10957 is <class 'list'>
list 10958 is <class 'list'>
list 10959 is <class 'list'>
list 10960 is <class 'list'>
list 10961 is <class 'list'>
list 10962 is 

list 11428 is <class 'list'>
list 11429 is <class 'list'>
list 11430 is <class 'list'>
list 11431 is <class 'list'>
list 11432 is <class 'list'>
list 11433 is <class 'list'>
list 11434 is <class 'list'>
list 11435 is <class 'list'>
list 11436 is <class 'list'>
list 11437 is <class 'list'>
list 11438 is <class 'list'>
list 11439 is <class 'list'>
list 11440 is <class 'list'>
list 11441 is <class 'list'>
list 11442 is <class 'list'>
list 11443 is <class 'list'>
list 11444 is <class 'list'>
list 11445 is <class 'list'>
list 11446 is <class 'list'>
list 11447 is <class 'list'>
list 11448 is <class 'list'>
list 11449 is <class 'list'>
list 11450 is <class 'list'>
list 11451 is <class 'list'>
list 11452 is <class 'list'>
list 11453 is <class 'list'>
list 11454 is <class 'list'>
list 11455 is <class 'list'>
list 11456 is <class 'list'>
list 11457 is <class 'list'>
list 11458 is <class 'list'>
list 11459 is <class 'list'>
list 11460 is <class 'list'>
list 11461 is <class 'list'>
list 11462 is 

list 11809 is <class 'list'>
list 11810 is <class 'list'>
list 11811 is <class 'list'>
list 11812 is <class 'list'>
list 11813 is <class 'list'>
list 11814 is <class 'list'>
list 11815 is <class 'list'>
list 11816 is <class 'list'>
list 11817 is <class 'list'>
list 11818 is <class 'list'>
list 11819 is <class 'list'>
list 11820 is <class 'list'>
list 11821 is <class 'list'>
list 11822 is <class 'list'>
list 11823 is <class 'list'>
list 11824 is <class 'list'>
list 11825 is <class 'list'>
list 11826 is <class 'list'>
list 11827 is <class 'list'>
list 11828 is <class 'list'>
list 11829 is <class 'list'>
list 11830 is <class 'list'>
list 11831 is <class 'list'>
list 11832 is <class 'list'>
list 11833 is <class 'list'>
list 11834 is <class 'list'>
list 11835 is <class 'list'>
list 11836 is <class 'list'>
list 11837 is <class 'list'>
list 11838 is <class 'list'>
list 11839 is <class 'list'>
list 11840 is <class 'list'>
list 11841 is <class 'list'>
list 11842 is <class 'list'>
list 11843 is 

list 12178 is <class 'list'>
list 12179 is <class 'list'>
list 12180 is <class 'list'>
list 12181 is <class 'list'>
list 12182 is <class 'list'>
list 12183 is <class 'list'>
list 12184 is <class 'list'>
list 12185 is <class 'list'>
list 12186 is <class 'list'>
list 12187 is <class 'list'>
list 12188 is <class 'list'>
list 12189 is <class 'list'>
list 12190 is <class 'list'>
list 12191 is <class 'list'>
list 12192 is <class 'list'>
list 12193 is <class 'list'>
list 12194 is <class 'list'>
list 12195 is <class 'list'>
list 12196 is <class 'list'>
list 12197 is <class 'list'>
list 12198 is <class 'list'>
list 12199 is <class 'list'>
list 12200 is <class 'list'>
list 12201 is <class 'list'>
list 12202 is <class 'list'>
list 12203 is <class 'list'>
list 12204 is <class 'list'>
list 12205 is <class 'list'>
list 12206 is <class 'list'>
list 12207 is <class 'list'>
list 12208 is <class 'list'>
list 12209 is <class 'list'>
list 12210 is <class 'list'>
list 12211 is <class 'list'>
list 12212 is 

In [1033]:
df['amenities_count']=df["amenities"].apply(lambda x: len(x))

In [1035]:
df['amenities_count']


0        31
1        16
2        12
3        22
4        33
         ..
12491    33
12492    30
12493    29
12494    30
12495    60
Name: amenities_count, Length: 12496, dtype: int64

In [1036]:
#convert instant book status to a boolean
dictionary_replace = {'t': True, 'f': False}
boolean_instant_bookable = df['instant_bookable'].map(dictionary_replace)
df["instant_bookable"] = boolean_instant_bookable
df.instant_bookable.unique() 

array([False,  True])

In [1044]:
#convert host since date into a float - the number of days the host has been on airbnb
df['host_since'] = pd.to_datetime(df['host_since'])    
df['host_experience_days'] = (df['host_since'] - df['host_since'].min())/ np.timedelta64(1,'D')
df['host_experience_days']

0        1371.0
1        2151.0
2        2971.0
3        3509.0
4        3236.0
          ...  
12491    3038.0
12492    3948.0
12493    3948.0
12494    3948.0
12495    4119.0
Name: host_experience_days, Length: 12496, dtype: float64

In [1046]:
df_final = df.drop(["host_since","amenities"], axis = 1) 
result = df_final.dtypes
print(result)

host_response_time              object
host_response_rate             float64
host_acceptance_rate           float64
host_is_superhost                 bool
host_total_listings_count      float64
host_has_profile_pic              bool
host_identity_verified            bool
neighbourhood_cleansed          object
latitude                       float64
longitude                      float64
property_type                   object
room_type                       object
accommodates                     int64
bedrooms                       float64
beds                           float64
price                          float64
minimum_nights                   int64
maximum_nights                   int64
availability_30                  int64
availability_60                  int64
availability_90                  int64
availability_365                 int64
number_of_reviews                int64
number_of_reviews_ltm            int64
number_of_reviews_l30d           int64
review_scores_rating     

In [1048]:
df_final.to_csv('Clean_AirbnbData.csv',index=False)

In [1049]:
df_final.shape

(12496, 36)